# Generated by Django 5.1.1 on 2024-09-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 26)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tasks',
            name='reminder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='time',
            field=models.TimeField(default='01:48:56'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
