# Generated by Django 5.1.1 on 2024-10-11 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0002_tasks_date_tasks_description_tasks_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time',
            field=models.TimeField(default='22:41:44'),
        ),
    ]
