# Generated by Django 5.1.1 on 2024-10-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0003_alter_tasks_completed_alter_tasks_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time',
            field=models.TimeField(default='22:40:20'),
        ),
        migrations.CreateModel(
            name='ListTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('competed', models.BooleanField(default=False)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Todo_app.list')),
            ],
        ),
    ]
