# Generated by Django 5.1.1 on 2024-10-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0004_list_alter_tasks_time_listtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='time',
        ),
    ]
